import { Inter } from 'next/font/google';
import './globals.css';

import './layout.scss';

import Header from './Components/Header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <div>
        <Header />
        <main className={inter.className}>{children}</main>
      </div>
    </html>
  );
}
